### ISSUE TITLE
Aborting installation. Unexpected error.

### ISSUE THREAD

**Issue by mimalef70** [firstlookmedia/react-scripts#37]
<img width="936" alt="screen shot 2018-05-28 at 1 06 09 pm" src="https://user-images.githubusercontent.com/17767869/40605581-0fec3c1c-6278-11e8-8000-bf49b99acd42.png">

Hi, i can'f solve this problem :)

**Comment by tomconroy** [comment]
Hi, it looks like the problem is we require `yarn` to be installed. You can install it with `brew install yarn`. I'll make a note in the readme
