### ISSUE TITLE
relative paths for static

### ISSUE THREAD

**Issue by ranmacar** [firstlookmedia/react-scripts#49]
Hi!

Is it possible to configure the path how build/static is included in the html? 
I'm deploying to a server that runs multiple react apps at different paths.

server.com/app1
server.com/app2

-> /static/... will look in server.com
-> static/... will look in server.com/appX

Or configure it to 'appX' and use /static/appX

**Comment by tomconroy** [comment]
hi! this repo is a fork of Facebook's. We don't support specifying the `homepage` in the same way the upstream repo does, but we'd review a PR which adds this support
