### ISSUE TITLE
question about how process.env is set in the front-end

### ISSUE THREAD

**Issue by ORESoftware** [firstlookmedia/react-scripts#7]
Hi! Was looking through this codebase to see where process.env might be set on the front-end in a `create-react-app` front-end application.

Having trouble doing figuring this out.
If you look at this thread:

https://github.com/facebookincubator/create-react-app/issues/1266

I am trying to figure out where process.env gets set. Usually it would be embedded in HTML, something like this:

```html

<script>

var process = {
     env: <%- data %>
};

window.process = process;

</script>
```

but I am not seeing this anywhere in your project, please let me know, thanks!

**Comment by ORESoftware** [comment]
ahhh, looks like it happens here:

https://github.com/facebookincubator/create-react-app/blob/92d9cda964b920b494774694cc9cef2f216e3cb4/packages/react-scripts/config/env.js

**Comment by tomconroy** [comment]
We have a separate project to handle server-sent configuration: https://github.com/firstlookmedia/env-config
